"""Builds `live_real`'s MJCF from a live ArUco calibration.

Unlike `box_clutter_real` (always exactly 3 obstacles, calibration only
repositions them, falling back to a real hardcoded pose when a tag is
not seen), `live_real` has no fixed obstacle layout at all: this module
regenerates its MJCF from scratch every run, with a plain worldbody
`<geom>` for exactly the obstacles that resolved this run's calibration
and nothing else -- zero, one, two or three, depending only on what was
actually detected. Called from `examples/pusht/pusht_real.py`'s `main`,
before `PushT` (and therefore the MuJoCo model) is built, since a
model's body count is fixed at compile time and cannot change afterward.

Kept entirely separate from `oim.worlds.real3d.run_real`'s own
`apply_obstacle_calibration`/`apply_obstacle_calibration_to_planner`,
which are `box_clutter_real`'s machinery (repositioning already-existing
mocap bodies) and are unchanged and unaffected by this module.

Live TF sampling is the only supported calibration source -- there is no
JSON-file fallback (removed; ArUco is always running when this scene is
used).
"""

from __future__ import annotations

import math
import time
from typing import Any, Dict, Tuple

from oim import ROOT

# The physical obstacles the lab's ArUco tags are glued to. Since
# 2026-09-05 these are 0.10 x 0.10 x 0.05 m cubes -- the same 0.10 m
# footprint as sim's single_obstacle cube (_TABLETOP_CUBE in
# oim/utils/scenes.py), half its height (material constraint; the stick
# works at ~0.025 m so a 0.05 m box still blocks it). Square footprint,
# so the tag's yaw only matters through the box's own edges (the old
# pudding boxes needed obs_3's size components swapped for its rotated
# tag; no longer). A detected "obs_N" can only ever be one of these, so
# there is nothing to measure at runtime beyond the SE(2) pose ArUco
# already gives. The tag -> obs_N_center offset lives in the perception
# repo (aruco_tf_broadcaster.py BOX_HALF_HEIGHT_M) and must match
# _OBSTACLE_HEIGHT_HALF: tag on the top face -> center 0.025 m below.
OBSTACLE_HALF_EXTENTS: Dict[str, Tuple[float, float]] = {
    "obs_1": (0.05, 0.05),
    "obs_2": (0.05, 0.05),
    "obs_3": (0.05, 0.05),
}
_OBSTACLE_HEIGHT_HALF = 0.025

LIVE_REAL_XML_PATH = ROOT + "/models/xarm6_pusht_tabletop_real/live_real.xml"

_HEADER = """<mujoco model="xarm6_pusht_live_real">
  <!-- GENERATED FILE -- do not hand-edit, and do not commit a
       hand-edited version over this. Written by
       oim.worlds.real3d.live_scene.write_live_real_xml from this run's
       own live ArUco calibration, immediately before PushT compiles the
       scene. Contains exactly the obstacles that resolved this run --
       see this module's own docstring. Regenerated by every run that
       loads --scene live_real; nothing detected writes the same bare
       table open_table_real.xml already is. -->
  <include file="common_real.xml"/>
  <include file="tee_real.xml"/>
  <worldbody>
    <camera name="front" pos="1.4907 0.3750 0.8684" xyaxes="0.0000 1.0000 -0.0000 -0.4226 0.0000 0.9063"/>
{bodies}  </worldbody>
</mujoco>
"""

_GEOM_TEMPLATE = (
    '    <geom class="obstacle" name="{name}" type="box" '
    'size="{hx:.4f} {hy:.4f} {hz:.4f}" '
    'pos="{x:.4f} {y:.4f} {hz:.4f}" euler="0 0 {yaw_deg:.2f}"/>\n'
)


def write_live_real_xml(
    calibration: Dict[str, Tuple[float, float, float]],
    out_path: str = LIVE_REAL_XML_PATH,
) -> None:
    """Render + write live_real.xml with one bare worldbody `<geom>` per
    obstacle actually present in `calibration` (SE(2) pose per name) --
    nothing else. `PushT.obstacle_geoms` already picks up any worldbody
    geom named "obs*" (see oim/tasks/pusht.py), so nothing there needs to
    change for a variable obstacle count."""
    bodies = "".join(
        _GEOM_TEMPLATE.format(
            name=name,
            hx=OBSTACLE_HALF_EXTENTS[name][0],
            hy=OBSTACLE_HALF_EXTENTS[name][1],
            hz=_OBSTACLE_HEIGHT_HALF,
            x=x, y=y, yaw_deg=math.degrees(yaw),
        )
        for name, (x, y, yaw) in calibration.items()
        if name in OBSTACLE_HALF_EXTENTS
    )
    with open(out_path, "w") as f:
        f.write(_HEADER.format(bodies=bodies))


def load_live_obstacle_calibration(
    verbose: bool = True,
) -> Dict[str, Tuple[float, float, float]]:
    """Sample obs_1/2/3 over TF right now, via a throwaway rclpy node
    (see `_sample_live_standalone`). Runs before `PushT`/`Ros2Interface`
    exist, so it cannot reuse either -- it is self-contained, the same
    rclpy.init/Node/Buffer/spin_once/shutdown lifecycle
    calibrate_obstacles.py itself used to use as a separate process, just
    inlined here as one. JSON-file calibration support was removed --
    live ArUco sampling is the only source now, `--obstacle-calibration`
    is a plain on/off flag.
    """
    if verbose:
        print("[live_real] sampling obs_1/2/3 live over TF "
              "(xarm_device -> obs_N_center) before building the scene...")
    calibration = _sample_live_standalone()
    missing = set(OBSTACLE_HALF_EXTENTS) - calibration.keys()
    if verbose:
        for name, (x, y, yaw) in calibration.items():
            print(f"[live_real] {name}: detected at "
                  f"({x:.4f}, {y:.4f})  yaw={math.degrees(yaw):.1f}deg")
        if missing:
            print(f"[live_real] no live TF for {sorted(missing)} -- "
                  f"is aruco_obstacle_node.py running on the perception "
                  f"laptop, and are those tags in view? live_real will "
                  f"simply not include {sorted(missing)} this run.")
    return calibration


def _sample_live_standalone(
    base_frame: str = "xarm_device", window_s: float = 1.5,
) -> Dict[str, Tuple[float, float, float]]:
    import rclpy  # noqa: PLC0415
    from rclpy.node import Node  # noqa: PLC0415
    from scipy.spatial.transform import Rotation  # noqa: PLC0415
    from tf2_ros import (  # noqa: PLC0415
        Buffer,
        ConnectivityException,
        ExtrapolationException,
        LookupException,
        TransformListener,
    )
    import numpy as np  # noqa: PLC0415

    started_here = not rclpy.ok()
    if started_here:
        rclpy.init()
    node = Node("live_real_scene_builder")
    buffer = Buffer()
    listener = TransformListener(buffer, node)  # noqa: F841 -- keeps the sub alive

    result: Dict[str, Tuple[float, float, float]] = {}
    try:
        for name in OBSTACLE_HALF_EXTENTS:
            target = f"{name}_center"
            samples = []
            t_end = time.time() + window_s
            while time.time() < t_end:
                rclpy.spin_once(node, timeout_sec=0.05)
                try:
                    tf = buffer.lookup_transform(
                        base_frame, target, rclpy.time.Time())
                    t = tf.transform.translation
                    q = tf.transform.rotation
                    yaw = Rotation.from_quat(
                        [q.x, q.y, q.z, q.w]).as_euler("xyz")[2]
                    samples.append((t.x, t.y, yaw))
                except (LookupException, ConnectivityException,
                        ExtrapolationException):
                    pass
            if not samples:
                continue
            arr = np.asarray(samples)
            mean_xy = arr[:, :2].mean(axis=0)
            mean_yaw = np.arctan2(
                np.sin(arr[:, 2]).mean(), np.cos(arr[:, 2]).mean())
            result[name] = (
                float(mean_xy[0]), float(mean_xy[1]), float(mean_yaw)
            )
    finally:
        node.destroy_node()
        if started_here:
            rclpy.shutdown()
    return result


def apply_live_obstacle_calibration_to_planner(
    task: Any,
    calibration: Dict[str, Tuple[float, float, float]],
    verbose: bool = True,
) -> None:
    """live_real's counterpart to `run_real.apply_obstacle_calibration_
    to_planner`: APPENDS one `Box` per detected obstacle to
    `task.object_model.obstacles.shapes` instead of replacing a
    fixed-index slot, since this scene starts with none (just the
    robot-base Circle -- see oim/utils/scenes.py's "live_real" entry).
    Must run after `PushT()` (task.object_model must exist) and before
    the controller's first `optimize` call -- same closure-vs-argument
    reasoning as `apply_obstacle_calibration_to_planner`'s own docstring.
    """
    from oim.objects import Box  # noqa: PLC0415

    shapes = task.object_model.obstacles.shapes
    for name, (x, y, yaw) in calibration.items():
        half_extents = OBSTACLE_HALF_EXTENTS.get(name)
        if half_extents is None:
            continue
        shapes.append(Box(center=[x, y], half_extents=half_extents, angle=yaw))
        if verbose:
            print(f"[live_real] {name}: added to planner obstacles <- "
                  f"center=({x:.4f}, {y:.4f})  angle={math.degrees(yaw):.1f}deg")
